In [1]:
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2024-08-23 15:09:43--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.008s  

2024-08-23 15:09:43 (129 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [2]:
with open("input.txt", "r", encoding="utf-8") as f:
  text = f.read()

In [3]:
print(f"length of dataset in characters: {len(text)}")

length of dataset in characters: 1115394


In [4]:
print(text[:100])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [5]:
chars = sorted(list(set(text)))
vocab_sz = len(chars)
print(''.join(chars))
print(vocab_sz)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [6]:
#creating a simple tokenizer
stoi = { ch:i for i,ch in enumerate(chars)}
itos = { i: ch for i,ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda c: ''.join([itos[i] for i in c])

print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [7]:
#encoding entirety of input text with tokenizer
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
data = torch.tensor(encode(text), dtype= torch.long)
print(data.shape, data.dtype)
print(data[:100])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [8]:
#90/10 data split
n = int(0.9*len(data))
train = data[:n]
val = data[n:]

print(train[:10])

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47])


In [9]:
#visualization of the autoregressive techniuque used by transformers for language modeling
block_sz = 8
x = train[:block_sz]
y = train[1:block_sz + 1]
for t in range(block_sz):
  context = x[:t+1]
  target = y[t]
  print(f"when input is {context} the target: {target}")


when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [10]:
torch.manual_seed(80)
batch_sz = 4 #number of input sequences to be processed in parallel
block_sz = 8 #maximum context length of predictions

def get_batch(split):
  #generate a small batch of data of inputs x and targets y
  data = train if split == 'train' else val
  ix = torch.randint(len(data) - block_sz, (batch_sz,))
  x = torch.stack([data[i:i+block_sz] for i in ix])
  y = torch.stack([data[i+1:i+block_sz+1] for i in ix])
  x, y = x.to(device), y.to(device)
  return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('-----')

for b in range(batch_sz): #batch dimension
  for t in range(block_sz): #time dimension
    context = xb[b,:t+1]
    target = yb[b,t]
    print(f"when the input is {context.tolist()}, the output is {target}")

inputs:
torch.Size([4, 8])
tensor([[52, 42,  1, 42, 47, 42,  1, 58],
        [39, 42, 50, 63,  1, 57, 54, 53],
        [51,  1, 58, 53,  1, 39, 50, 50],
        [63, 53, 59,  6,  1, 59, 52, 41]], device='cuda:0')
targets:
torch.Size([4, 8])
tensor([[42,  1, 42, 47, 42,  1, 58, 56],
        [42, 50, 63,  1, 57, 54, 53, 49],
        [ 1, 58, 53,  1, 39, 50, 50, 11],
        [53, 59,  6,  1, 59, 52, 41, 50]], device='cuda:0')
-----
when the input is [52], the output is 42
when the input is [52, 42], the output is 1
when the input is [52, 42, 1], the output is 42
when the input is [52, 42, 1, 42], the output is 47
when the input is [52, 42, 1, 42, 47], the output is 42
when the input is [52, 42, 1, 42, 47, 42], the output is 1
when the input is [52, 42, 1, 42, 47, 42, 1], the output is 58
when the input is [52, 42, 1, 42, 47, 42, 1, 58], the output is 56
when the input is [39], the output is 42
when the input is [39, 42], the output is 50
when the input is [39, 42, 50], the output is 63
wh

### FEEDING OUR PREPROCESSED TRAINING DATA INTO NEURAL NETWORKS

1. THE BI-GRAM LANGUAGE MODEL
    A simple language model that predicts the next token in the sequence based on the single previous token. Can be extended to predict based on n preceding tokens (n-gram model)

In [11]:
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(80)

#model hyperparameters
batch_size = 32
block_size = 8
max_iters = 3000
eval_interval = 300
learning_rate = 1e-2
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200

class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_sz):
      super().__init__()
      #each token directly reads off the logits for the next token in a lookup table
      self.token_embedding_table = nn.Embedding(vocab_sz, vocab_sz)

    def forward(self, idx, targets=None):
      #both idx and tensor are 2-dimensional (B,T) tensor of integers
      logits = self.token_embedding_table(idx) #(B, T, C)

      if targets == None:
        loss = None
      else:
        #since pytorch expects a (B,C,T) tensor, we reshape the tensor using torch.view()
        B,T,C = logits.shape
        logits = logits.view(B*T,C)
        targets = targets.view(B*T) #combining our batch and time dimensions

        loss = F.cross_entropy(logits, targets) #negative log-likehood loss fn
      return logits, loss

    def generate(self, idx, max_new_tokens):
      for _ in range(max_new_tokens):
        # we pass our indexes to the forward fn to get our predictions(logits)
        logits , loss = self(idx)
        # focus on only the last time step
        logits = logits[:, -1, :] # becomes (B,C)
        #convert predictions to class probabilities
        probs = F.softmax(logits, dim=-1) #(B,C)
        # sample from the prob. distribution
        idx_next = torch.multinomial(probs, num_samples=1)
        # append sampled index to running sequence
        idx = torch.cat((idx, idx_next), dim=1)
      return idx


model = BigramLanguageModel(vocab_sz)
m = model.to(device)
logits, loss = m(xb, yb)

print(logits)
print(logits.shape)
print(loss) #NOTE: ideal nll loss = -ln(1/vocab_sz)

tensor([[ 1.2811, -0.2446,  0.3116,  ...,  0.2522, -0.0340, -0.8544],
        [-0.0927, -1.2656, -2.1652,  ..., -0.0186,  0.9552,  1.3387],
        [-0.3464, -1.1768, -2.6356,  ...,  1.7470,  1.1502, -0.0674],
        ...,
        [ 1.0463, -0.3701,  1.5730,  ...,  0.1144,  1.5161,  1.6939],
        [ 1.2811, -0.2446,  0.3116,  ...,  0.2522, -0.0340, -0.8544],
        [ 0.9166, -0.5317, -0.2654,  ...,  0.3093, -0.0615, -0.7909]],
       device='cuda:0', grad_fn=<ViewBackward0>)
torch.Size([32, 65])
tensor(4.7332, device='cuda:0', grad_fn=<NllLossBackward0>)


In [12]:
char_seq = m.generate(torch.zeros((1,1), dtype= torch.long, device=device), max_new_tokens=100)[0].tolist() #generate a sequence of 100 characters using a newline character as initial idx
print(decode(char_seq)) #prev op returns vaiid tokenizer idxs which we then decode


zZT.Or:,Fk xfWv$hUNy&rz
XdR
eyIQfX
m,PqRTTZgFXTGyYcWW.zz
lrP3Ek&nX
M:o'GG.U&bl;YV.:priXCIxi.:NJADm&Y


In [13]:
@torch.no_grad()
def estimate_loss():
  out = {}
  model.eval()
  for split in ['train','val']:
    losses = torch.zeros(eval_iters)
    for k in range(eval_iters):
      X, y = get_batch(split)
      logits, loss = model(X,y)
      losses[k] = loss.item()
    out[split] = losses.mean()
  model.train()
  return out

In [14]:
#create our optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-2)

In [15]:
for iter in range(max_iters):
  if iter % eval_interval == 0:
    losses = estimate_loss()
    print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

  xb, yb = get_batch('train')


  logits , loss = model(xb, yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

step 0: train loss 4.5679, val loss 4.5684
step 300: train loss 3.1709, val loss 3.1705
step 600: train loss 2.7391, val loss 2.7489
step 900: train loss 2.6082, val loss 2.6197
step 1200: train loss 2.5575, val loss 2.5715
step 1500: train loss 2.5117, val loss 2.5468
step 1800: train loss 2.4863, val loss 2.5187
step 2100: train loss 2.4889, val loss 2.5019
step 2400: train loss 2.5030, val loss 2.5177
step 2700: train loss 2.4793, val loss 2.4975


In [16]:
context = torch.zeros((1,1), dtype= torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=500)[0].tolist()))


INo an ppr y lyoug. S:
NI r sthe he bes, h
Ormand mend hincly,
prthod afot dotors sl bethred,



wiste hicint att y,coresld, t courshowaselve J&hy, phowis area, e pssayofo he hout;
JUKELE:
BRCK:rist iranoowinds TUS:
Fowo d I indurdge, su dsuner f t d wnder hin?
AShorin thot! wey m l n Noy OLLxayene se chatrilRELIIOREENENVe osinthor s s; it f ded gealor watiblin
UNow 'Manuge e ay WAD$Tod nt.
BRUSadenddend id t whe itha t?Be dds oungoure therme t or am


Bure cam coumaus pt berghe shighang f hephe


2. The Transformer model

THE MATHEMATICAL TRICK IN SELF-ATTENTION

In [17]:
torch.manual_seed(32)
B,T, C = 4,8,2
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

We want to somehow use aggregate info from prevoius tokens in the past to predict the present while disregarding future tokens. We can do this in a number of ways.

In [18]:
# 1. x[b,t] = mean_{i<=t} x[b,i]

xbow = torch.zeros((B,T,C))
for b in range(B):
  for t in range(T):
    xprev = x[b, :t+1]
    xbow[b,t] = torch.mean(xprev, 0)

In [19]:
x[0]

tensor([[-1.7416, -0.3635],
        [ 0.9803, -1.7387],
        [ 0.3530, -0.2026],
        [-0.5071,  0.2125],
        [-1.0660,  0.7092],
        [-0.3287, -0.2406],
        [-0.3393, -1.3003],
        [-1.3534,  0.0349]])

In [20]:
xbow[0]

tensor([[-1.7416, -0.3635],
        [-0.3806, -1.0511],
        [-0.1361, -0.7683],
        [-0.2288, -0.5231],
        [-0.3963, -0.2766],
        [-0.3850, -0.2706],
        [-0.3785, -0.4177],
        [-0.5003, -0.3612]])

In [21]:
#2. we manipulate the output of matmul by modifying the multiplying matrix a in such a way the output t+1 is a average of the preceding outputs t
torch.manual_seed(42)
a = torch.tril(torch.ones(3,3))
a = a / torch.sum(a,1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print(a)
print(b)
print(c)

tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [22]:
#therefore
w = torch.tril(torch.ones(T,T))
w = w / w.sum(1, keepdim=True)
xbow2 = w @ x # (B(auto-created by torch for matmul), T, T) @ (B, T, C) ---> (B,T,C)
xbow2[0]

tensor([[-1.7416, -0.3635],
        [-0.3806, -1.0511],
        [-0.1361, -0.7683],
        [-0.2288, -0.5231],
        [-0.3963, -0.2766],
        [-0.3850, -0.2706],
        [-0.3785, -0.4177],
        [-0.5003, -0.3612]])

In [23]:
# 3. using softmax (multicategory equivalent of the sigmoid fn)
t_tril = torch.tril(torch.ones(T,T))
t_w = torch.zeros((T,T))
t_w = t_w.masked_fill(t_tril == 0, float("-inf"))
t_w = F.softmax(w, dim=-1)
xbow3 = t_w @ x
xbow3[0]

tensor([[-1.7416, -0.3635],
        [-0.3806, -1.0511],
        [-0.1361, -0.7683],
        [-0.2288, -0.5231],
        [-0.3963, -0.2766],
        [-0.3850, -0.2706],
        [-0.3785, -0.4177],
        [-0.5003, -0.3612]])

In [24]:
#4. Self-attention!
torch.manual_seed(80)
head_size = 16
sa_B,sa_T,sa_C = 4,8,32
x= torch.randn(sa_B, sa_T, sa_C)

#self-attention using a single head
sa_key = nn.Linear(sa_C, head_size, bias=False)
sa_query = nn.Linear(sa_C, head_size, bias=False)
sa_value = nn.Linear(sa_C, head_size, bias= False)
sa_k = sa_key(x) #(B,T,16) stores some information content about the token
sa_q = sa_query(x) # stores information context of the token
sa_v = sa_value(x)

# matmul of q and k produce attention scores which represent the degree of affinity (similarity) between input tokens
weights = sa_q @ sa_k.transpose(-2, -1) # (B, T, 16) * (B, 16, T) --> (B, T, T)
tril = torch.t_tril(torch.ones(T,T))
weights = weights.masked_fill(t_tril== 0, float('-inf'))
weights = F.softmax(weights, dim=-1)
out = weights @ sa_v

out.shape

torch.Size([4, 8, 16])

IMPLEMENTING OUR TRANSFORMER MODEL

In [14]:
import torch
import torch.nn as nn
import torch.nn.functional as F

#hyperparameters
batch_sz = 64
block_sz = 256
max_iters = 5000
eval_interval = 500
learning_rate = 3e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 384
n_head = 6
n_layer = 6
dropout = 0.2


def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train if split == 'train' else val
    ix = torch.randint(len(data) - block_sz, (batch_sz,))
    x = torch.stack([data[i:i+block_sz] for i in ix])
    y = torch.stack([data[i+1:i+block_sz+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
  out = {}
  model.eval()
  for split in ['train','val']:
    losses = torch.zeros(eval_iters)
    for k in range(eval_iters):
      X, y = get_batch(split)
      logits, loss = model(X,y)
      losses[k] = loss.item()
    out[split] = losses.mean()
  model.train()
  return out

class Head(nn.Module):
  """ implementation of one head of self-attention"""
  def __init__(self, head_sz):
    super().__init__()
    self.key = nn.Linear(n_embd, head_sz, bias=False)
    self.query = nn.Linear(n_embd, head_sz, bias=False)
    self.value = nn.Linear(n_embd, head_sz, bias=False)
    self.register_buffer('tril', torch.tril(torch.ones(block_sz, block_sz)))
    self.dropout = nn.Dropout(dropout)

  def forward(self,x):
    B,T,C = x.shape

    k = self.key(x)
    q = self.query(x)
    W = q @ k.transpose(-2,-1) * k.shape[-1]**-0.5
    W = W.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
    W = F.softmax(W, dim=-1)
    W = self.dropout(W)

    v = self.value(x)
    out = W @ v
    return out

class MultiHeadAttention(nn.Module):
  """ multiple heads of self-attention in parallel"""
  def __init__(self, head_sz, num_heads):
    super().__init__()
    self.heads = nn.ModuleList([Head(head_sz) for _ in range(num_heads)])
    self.proj = nn.Linear(head_sz * num_heads, n_embd)
    self.dropout = nn.Dropout(dropout)

  def forward(self, x):
    out = torch.cat([h(x) for h in self.heads], dim=-1)
    proj = self.proj(x)
    out = self.dropout(proj)
    return out


class FeedForward(nn.Module):
  """ MLP layer with dropout """
  def __init__(self, n_embd):
    super().__init__()
    self.net = nn.Sequential(
      nn.Linear(n_embd, 4 * n_embd), #attention paper uses 1:4 input to inner-layer dimensionality
      nn.ReLU(),
      nn.Linear(4 * n_embd, n_embd),
      nn.Dropout(dropout),
    )

  def forward(self, x):
    return self.net(x)


class Block(nn.Module):
  """ Transformer block: communication followed by computation"""
  def __init__(self, n_embd, n_head):
    super().__init__()
    head_sz = n_embd // n_head
    self.s_attn = MultiHeadAttention(head_sz, n_head)
    self.ffwd = FeedForward(n_embd)
    self.ln1 = nn.LayerNorm(n_embd)
    self.ln2 = nn.LayerNorm(n_embd)

  def forward(self, x):
    x = x + self.s_attn(self.ln1(x)) #skip connections as our nn gets more dense
    x = x + self.ffwd(self.ln2(x))
    return x

class GPTLanguageModel(nn.Module):
    """ Putting it together """
    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_sz, n_embd)
        self.position_embedding_table = nn.Embedding(block_sz, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_sz)

        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_sz:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = GPTLanguageModel()
m = model.to(device)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')



#optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=learning_rate)

#training loop
for iter in range(max_iters):
  if iter % eval_interval == 0 or iter == max_iters - 1: #at intervals of 500 or at 4999
    losses = estimate_loss()

    print(f"step {iter} : training loss {losses['train']:.4f}, validation loss: {losses['val']:.4f}")


  xb, yb = get_batch('train')

  logits, loss = m(xb, yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

10.788929 M parameters
step 0 : training loss 4.3129, validation loss: 4.3103
step 500 : training loss 2.4649, validation loss: 2.4903
step 1000 : training loss 2.4593, validation loss: 2.4827
step 1500 : training loss 2.4615, validation loss: 2.4888
step 2000 : training loss 2.4591, validation loss: 2.4861
step 2500 : training loss 2.4578, validation loss: 2.4808
step 3000 : training loss 2.4583, validation loss: 2.4865


KeyboardInterrupt: 

In [ ]:
context = torch.zeros((1,1), dtype= torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=500)[0].tolist()))